// Generated by gencpp from file pcl_filter_msgs/ShapeFilter.msg
// DO NOT EDIT!


#ifndef PCL_FILTER_MSGS_MESSAGE_SHAPEFILTER_H
#define PCL_FILTER_MSGS_MESSAGE_SHAPEFILTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pcl_filter_msgs
{
template <class ContainerAllocator>
struct ShapeFilter_
{
  typedef ShapeFilter_<ContainerAllocator> Type;

  ShapeFilter_()
    : status(false)
    , color(0)
    , shape(0)
    , radius(0.0)  {
    }
  ShapeFilter_(const ContainerAllocator& _alloc)
    : status(false)
    , color(0)
    , shape(0)
    , radius(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef int32_t _color_type;
  _color_type color;

   typedef int32_t _shape_type;
  _shape_type shape;

   typedef double _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> const> ConstPtr;

}; // struct ShapeFilter_

typedef ::pcl_filter_msgs::ShapeFilter_<std::allocator<void> > ShapeFilter;

typedef boost::shared_ptr< ::pcl_filter_msgs::ShapeFilter > ShapeFilterPtr;
typedef boost::shared_ptr< ::pcl_filter_msgs::ShapeFilter const> ShapeFilterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator1> & lhs, const ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.color == rhs.color &&
    lhs.shape == rhs.shape &&
    lhs.radius == rhs.radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator1> & lhs, const ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pcl_filter_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bac0e40fde6119b59e2c4c499c9c9f1b";
  }

  static const char* value(const ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbac0e40fde6119b5ULL;
  static const uint64_t static_value2 = 0x9e2c4c499c9c9f1bULL;
};

template<class ContainerAllocator>
struct DataType< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pcl_filter_msgs/ShapeFilter";
  }

  static const char* value(const ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"int32 color\n"
"int32 shape        \n"
"float64 radius\n"
;
  }

  static const char* value(const ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.color);
      stream.next(m.shape);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShapeFilter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pcl_filter_msgs::ShapeFilter_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "color: ";
    Printer<int32_t>::stream(s, indent + "  ", v.color);
    s << indent << "shape: ";
    Printer<int32_t>::stream(s, indent + "  ", v.shape);
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCL_FILTER_MSGS_MESSAGE_SHAPEFILTER_H
